import { CarouselTemplate } from './templates';

export const TEMPLATES_NEW_NICHES: CarouselTemplate[] = [

  // ══════════════════════════════════════════
  // QUICK WINS — more generic + niche specific
  // ══════════════════════════════════════════
  {
    id: 'quick-wins-google-reviews',
    label: 'Quick Wins: Get 20 Google Reviews This Month',
    desc: '5 moves that generate a flood of Google reviews fast',
    icon: '⭐',
    category: 'Quick Wins',
    format: 'quick-wins',
    topic: '5 fast moves to get 20 new Google reviews this month for any local service business',
    cards: [
      { type: 'cover', eyebrow: 'QUICK WINS', headline: 'HOW TO GET 20 GOOGLE REVIEWS THIS MONTH', subheadline: 'The exact texts and systems that generate reviews on autopilot — no begging required.', tag: 'REPUTATION' },
      { type: 'quick-win', eyebrow: 'MOVE #1', headline: 'TEXT YOUR LAST 30 CUSTOMERS RIGHT NOW', body: '"Hey [name], it\'s [your name] from [company]. We really appreciate your business — if you have 60 seconds, a Google review would mean the world to us and helps other homeowners find us. Here is the link: [link]" Send it. Expect 20-30% to leave one within 48 hours. That is 6-9 reviews from one text blast.', lesson: 'The best time to ask for a review is immediately after a great experience. Second best time is right now.', lessonLabel: 'DO THIS NOW', slideNumber: 1, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'MOVE #2', headline: 'ADD THE REVIEW LINK TO YOUR EMAIL SIGNATURE', body: 'Add one line to every email you send: "Happy with our work? Leave us a quick Google review here: [link]" Every invoice, every follow-up, every estimate reply now passively drives reviews. Setup time: 3 minutes.', lesson: 'Every email you send is a review request you are currently not sending.', lessonLabel: 'DO THIS TODAY', slideNumber: 2, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'MOVE #3', headline: 'PUT A QR CODE ON YOUR INVOICES AND DOOR HANGERS', body: 'Generate a Google review QR code (free at qr-code-generator.com). Put it on your paper invoice, your door hangers, your vehicle magnet, and your yard signs. Label it: "Loved our work? Scan to leave a quick review." Physical touchpoints generate 12-18% scan-to-review rates.', lesson: 'Every piece of paper that leaves your hands is a review opportunity.', lessonLabel: 'DO THIS WEEK', slideNumber: 3, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'MOVE #4', headline: 'RESPOND TO EVERY EXISTING REVIEW TODAY', body: 'Go to your Google Business Profile right now. Respond to every review — 5 stars and 1 star alike. Google\'s algorithm ranks businesses higher when the owner actively engages. This alone improves your map pack position within 2-3 weeks. Bonus: potential customers read your responses more than the reviews themselves.', lesson: 'Responding to reviews is free marketing. Most businesses ignore it completely.', lessonLabel: 'DO THIS TODAY', slideNumber: 4, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'MOVE #5', headline: 'AUTOMATE IT — NEVER ASK MANUALLY AGAIN', body: 'Set up a GHL automation: job marked complete → wait 2 hours → text fires automatically with your review link. Every single job generates a review request without you touching it. At 20-25% response rate on 10 jobs per week — that is 2-3 new reviews per week, 100+ per year. Completely automated.', lesson: 'Manual review requests get forgotten. Automated review requests compound forever.', lessonLabel: 'BUILD THE SYSTEM', slideNumber: 5, totalSlides: 6 },
      { type: 'cta', eyebrow: 'AUTOMATE IT', headline: 'WANT YOUR REVIEW SYSTEM BUILT AND RUNNING THIS WEEK?', body: 'Post-job review request automation, QR code setup, and response templates — all done for you.', ctaText: 'Book a Free Demo' },
    ],
  },
  {
    id: 'quick-wins-referrals',
    label: 'Quick Wins: Referral System That Pays',
    desc: '5 moves to turn your best customers into your best salespeople',
    icon: '🤝',
    category: 'Quick Wins',
    format: 'quick-wins',
    topic: '5 quick moves to build a referral system that generates consistent word-of-mouth leads',
    cards: [
      { type: 'cover', eyebrow: 'QUICK WINS', headline: 'TURN YOUR BEST CUSTOMERS INTO YOUR BEST SALESPEOPLE', subheadline: 'The referral system that generates consistent leads without spending a dollar on ads.', tag: 'REFERRALS' },
      { type: 'quick-win', eyebrow: 'MOVE #1', headline: 'CALL YOUR TOP 10 CLIENTS AND JUST ASK', body: '"Hey [name], I wanted to reach out personally — you have been a great client and I really appreciate you. Quick question — do you know anyone who might need [service]? I would love to take care of your network the same way I take care of you." Simple, direct, personal. Expect 3-4 referrals from 10 calls. Takes 20 minutes.', lesson: 'The number one reason customers do not refer is that nobody asked them.', lessonLabel: 'DO THIS TODAY', slideNumber: 1, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'MOVE #2', headline: 'OFFER AN IMMEDIATE REWARD — NOT A FUTURE CREDIT', body: '"Refer someone who books with us and we will send you a $50 gift card to [local restaurant] immediately — not a service credit, actual cash in your hand." Immediate tangible rewards convert 3x better than service credits. Send the gift card the same day they refer, not after the job completes.', lesson: 'Delayed rewards get forgotten. Immediate rewards get shared.', lessonLabel: 'THE MECHANIC', slideNumber: 2, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'MOVE #3', headline: 'TEXT YOUR REFERRAL PROGRAM AFTER EVERY 5-STAR REVIEW', body: 'When someone leaves a 5-star review — wait 2 days, then text: "Thank you so much for that amazing review [name] — it means everything to us. Quick question: do you know anyone else who could use our help? If you refer them and they book, I will send you a $[reward] gift card as a thank you." Strike while the appreciation is fresh.', lesson: 'The 48 hours after a 5-star review is the highest-referral-probability window you will ever have.', lessonLabel: 'THE TIMING', slideNumber: 3, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'MOVE #4', headline: 'CREATE A SHAREABLE CARD FOR EVERY COMPLETED JOB', body: 'After every job: text the customer a before/after photo with: "Feel free to share this with anyone who might need [service] — we are taking new clients in [area] this month." 35-40% will share it on their own to neighbors and family groups. Zero reward needed when the content is shareable on its own.', lesson: 'Great work is referral content. You just have to make it easy to share.', lessonLabel: 'THE ASSET', slideNumber: 4, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'MOVE #5', headline: 'BUILD THE AUTOMATED REFERRAL SEQUENCE', body: 'GHL workflow: 3 days after job complete → text asking for referral. If they refer → immediate thank you + gift card trigger. If referred person books → text the original referrer with confirmation. The whole sequence runs without you. Most clients see 1 referral per 5 active customers per month just from the automation.', lesson: 'A referral system that runs automatically is worth 10x one that depends on you remembering.', lessonLabel: 'THE SYSTEM', slideNumber: 5, totalSlides: 6 },
      { type: 'cta', eyebrow: 'BUILD IT', headline: 'WANT YOUR REFERRAL SYSTEM AUTOMATED IN GHL THIS WEEK?', body: 'Post-review referral request, reward fulfillment trigger, and follow-up sequence — all built and running.', ctaText: 'Book a Free Demo' },
    ],
  },
  {
    id: 'quick-wins-med-spa',
    label: 'Quick Wins: Med Spa & Aesthetic Clinic',
    desc: '5 fast moves to fill your treatment calendar this week',
    icon: '💆',
    category: 'Industry: Med Spa & Aesthetics',
    format: 'quick-wins',
    topic: '5 quick wins for med spas and aesthetic clinics to fill their calendar and increase revenue',
    cards: [
      { type: 'cover', eyebrow: 'QUICK WINS', headline: '5 QUICK WINS TO FILL YOUR MED SPA CALENDAR THIS WEEK', subheadline: 'No new ad budget. Just smarter moves with your existing client base.', tag: 'MED SPA' },
      { type: 'quick-win', eyebrow: 'WIN #1', headline: 'TEXT EVERY CLIENT DUE FOR A TOUCH-UP', body: '"Hey [name], it has been about [X weeks] since your last [treatment] — you are right in the window for your touch-up to maintain the best results. We have some openings this week and next. Want me to hold a spot for you?" Botox, filler, and laser clients have predictable maintenance cycles. Work your schedule.', lesson: 'Your existing clients are your highest-margin revenue. They already trust you — they just need the reminder.', lessonLabel: 'DO THIS NOW', slideNumber: 1, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'WIN #2', headline: 'LAUNCH A "BRING A FRIEND" PROMO FOR ONE WEEK', body: '"Book any treatment this week and bring a friend — they get 20% off their first visit and you get a $50 credit on your account." Run it for 7 days. Text your entire client list on day 1. Expect 15-25% response rate. Each referral is worth $300-$800 in lifetime value.', lesson: 'Existing clients referring friends have a 70%+ first-visit show rate vs 40% from ads.', lessonLabel: 'DO THIS WEEK', slideNumber: 2, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'WIN #3', headline: 'POST A BEFORE/AFTER WITH CLIENT PERMISSION TODAY', body: 'Reach out to your 5 best result clients from the last 60 days. Ask permission to post their before/after. Offer a $50 credit as a thank you. Post on Instagram and Facebook with a specific CTA: "DM me the word RESULTS and I will send you our current availability." Before/afters convert at 4-6x the rate of any other aesthetic content.', lesson: 'Social proof from real clients you treated is more powerful than any ad you can run.', lessonLabel: 'DO THIS TODAY', slideNumber: 3, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'WIN #4', headline: 'UPSELL AT CHECKOUT — ONE SIMPLE QUESTION', body: '"While you are here — have you thought about [complementary treatment]? A lot of our clients who do [what they just had] also love [the add-on] because [specific benefit]. We actually have time this afternoon if you wanted to add it on." Upsell at point of service converts 30-40% of the time when framed as a natural next step.', lesson: 'The easiest sale you will ever make is to a client who is already in your chair.', lessonLabel: 'DO THIS TODAY', slideNumber: 4, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'WIN #5', headline: 'REACTIVATE LAPSED CLIENTS (90+ DAYS SILENT)', body: '"Hey [name], it has been a while — we miss you! We have some exciting new treatments we think you would love, and we would love to catch up. I am holding a spot for you at a special returning-client rate. Want to see what is new?" Lapsed clients reactivate at 25-35% when reached out to personally within 6 months of their last visit.', lesson: 'A client who came once and did not come back is not lost — they just need an invitation.', lessonLabel: 'DO THIS WEEK', slideNumber: 5, totalSlides: 6 },
      { type: 'cta', eyebrow: 'AUTOMATE IT', headline: 'WANT YOUR MED SPA CLIENT RETENTION SYSTEM BUILT?', body: 'Reactivation sequences, touch-up reminders, post-visit upsell flows, and review automation — all done for you.', ctaText: 'Book a Free Demo' },
    ],
  },
  {
    id: 'quick-wins-local-restaurant',
    label: 'Quick Wins: Local Restaurant & Coffee Shop',
    desc: '5 fast moves to increase repeat visits and average ticket',
    icon: '☕',
    category: 'Industry: Restaurant & Cafe',
    format: 'quick-wins',
    topic: '5 quick wins for local restaurants and coffee shops to increase repeat customers and revenue per visit',
    cards: [
      { type: 'cover', eyebrow: 'QUICK WINS', headline: '5 QUICK WINS FOR LOCAL RESTAURANTS THIS WEEK', subheadline: 'Turn one-time visitors into regulars and regulars into brand ambassadors.', tag: 'HOSPITALITY' },
      { type: 'quick-win', eyebrow: 'WIN #1', headline: 'START COLLECTING PHONE NUMBERS AT CHECKOUT', body: '"Want a $5 off coupon for your next visit? Just drop your number here." A simple table card or POS prompt. Build your SMS list. 50 numbers per week = 2,600 per year. That list is worth thousands in reactivation campaigns you can run anytime business is slow.', lesson: 'Every customer who walks out without their number in your system is a customer you cannot market to again.', lessonLabel: 'START TODAY', slideNumber: 1, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'WIN #2', headline: 'TEXT YOUR LIST EVERY SLOW DAY', body: '"Hey [name], it is [day] and we just pulled [signature item] out of the oven. First [X] people in get a free [add-on]. See you soon!" Send it at 10am for lunch traffic, 3pm for dinner. Restaurant SMS campaigns average 25-35% redemption rates — far higher than email or social. One text on a Tuesday can fill a slow afternoon.', lesson: 'A restaurant with a text list can create demand on any slow day in 3 minutes.', lessonLabel: 'DO THIS WEEK', slideNumber: 2, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'WIN #3', headline: 'TRAIN STAFF TO UPSELL ONE THING PER TABLE', body: '"Can I recommend our [seasonal item]? It pairs really well with what you ordered and a lot of people have been loving it this week." One upsell per table at $4-8 average. 20 tables per day = $80-$160 in daily revenue added. $2,400-$4,800 per month from one trained habit across your team.', lesson: 'The average restaurant leaves $3-8 on every table by not upselling. That adds up to tens of thousands per year.', lessonLabel: 'TRAIN THIS WEEK', slideNumber: 3, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'WIN #4', headline: 'POST YOUR BEHIND-THE-SCENES TODAY', body: 'Film 60 seconds of your morning prep, your team making something, or your owner talking about why they started the business. Post it on Instagram and TikTok. Behind-the-scenes content for local restaurants gets 3-5x more reach than polished food photography. Authenticity drives foot traffic better than any ad.', lesson: 'People buy from people. Show them who you are and they will come see you.', lessonLabel: 'DO THIS TODAY', slideNumber: 4, totalSlides: 6 },
      { type: 'quick-win', eyebrow: 'WIN #5', headline: 'RESPOND TO EVERY GOOGLE REVIEW IN THE NEXT HOUR', body: 'Go to your Google Business Profile right now. Respond to every review — 5 stars and 1 star. Use the customer\'s name. Thank them specifically for what they mentioned. Google rewards active profiles with higher map pack rankings. Most restaurants do this for one week then stop. Do it forever.', lesson: 'A restaurant that responds to every review appears more trustworthy than a competitor with twice the reviews.', lessonLabel: 'DO THIS NOW', slideNumber: 5, totalSlides: 6 },
      { type: 'cta', eyebrow: 'BUILD THE SYSTEM', headline: 'WANT YOUR SMS LIST AND REACTIVATION CAMPAIGNS BUILT FOR YOU?', body: 'Text list collection, slow-day campaigns, loyalty flows, and review automation — done for you.', ctaText: 'Book a Free Demo' },
    ],
  },

  // ══════════════════════════════════════════
  // HOT TAKES
  // ══════════════════════════════════════════
  {
    id: 'hot-takes-marketing-myths',
    label: 'Hot Takes: Marketing Myths Contractors Believe',
    desc: 'The popular beliefs that are quietly killing contractor businesses',
    icon: '🔥',
    category: 'Hot Takes',
    format: 'hot-take',
    topic: 'The biggest marketing myths that home service contractors believe that cost them money',
    cards: [
      { type: 'cover', eyebrow: 'HOT TAKES', headline: 'THE MARKETING MYTHS QUIETLY KILLING CONTRACTOR BUSINESSES', subheadline: 'Popular beliefs. Expensive lies. Here is what is actually true.', tag: 'UNPOPULAR TRUTH' },
      { type: 'hot-take', eyebrow: 'MYTH #1', headline: '"WORD OF MOUTH IS ENOUGH"', body: 'Word of mouth is a revenue ceiling, not a strategy. It scales to the size of your existing network and then stops. The most referral-heavy contractors still cap out at $400-600k because the referral pool runs dry. The $2M companies have word of mouth AND a system. Referrals feed the machine — they are not the machine.', slideNumber: 1, totalSlides: 7 },
      { type: 'hot-take', eyebrow: 'MYTH #2', headline: '"I NEED MORE LEADS"', body: 'You probably need more follow-up. The average contractor follows up 1.2 times after sending an estimate. The data says most buying decisions happen on touch 4-7. You are leaving 60-70% of closeable deals on the table because you gave up before the customer was ready. More leads with the same follow-up is more money wasted.', slideNumber: 2, totalSlides: 7 },
      { type: 'hot-take', eyebrow: 'MYTH #3', headline: '"FACEBOOK ADS DO NOT WORK FOR MY NICHE"', body: 'Facebook ads work for every local service niche. What does not work is sending ad traffic to your homepage with no follow-up system. The ad is 20% of the result. The landing page and the follow-up automation are the other 80%. Most contractors run ads, collect leads, and then email them once. That is not an ad problem.', slideNumber: 3, totalSlides: 7 },
      { type: 'hot-take', eyebrow: 'MYTH #4', headline: '"LOWERING MY PRICE WILL GET ME MORE JOBS"', body: 'Lowering your price attracts price shoppers — the worst clients in any market. They negotiate harder, complain more, leave worse reviews, and never refer. Raising your price by 15-20% and losing 20% of estimates makes you more money with less work and better clients. The contractors I know who make $500k+ raised prices first.', slideNumber: 4, totalSlides: 7 },
      { type: 'hot-take', eyebrow: 'MYTH #5', headline: '"I DO NOT NEED MARKETING — MY WORK SPEAKS FOR ITSELF"', body: 'Great work earns repeat business from people who experienced it. It does not attract new customers who have never heard of you. A mediocre contractor with 200 Google reviews and a consistent follow-up system will outsell a great contractor with 12 reviews and no system every single time. Quality is the minimum. Marketing is the multiplier.', slideNumber: 5, totalSlides: 7 },
      { type: 'hot-take', eyebrow: 'MYTH #6', headline: '"REVIEWS DO NOT REALLY MATTER"', body: '87% of consumers read reviews before contacting a local service company. In roofing, tree service, HVAC, and lawn care — the company with 100+ reviews at 4.8 stars wins the call before anyone speaks a word. Reviews are not social proof — they are the first sales conversation happening without you in the room.', slideNumber: 6, totalSlides: 7 },
      { type: 'cta', eyebrow: 'THE SYSTEM', headline: 'THE CONTRACTORS WINNING ARE DOING THE OPPOSITE OF ALL OF THESE', body: 'Follow-up automation, review collection, lead nurture, and pricing confidence — all built into one system.', ctaText: 'Book a Free Demo' },
    ],
  },
  {
    id: 'hot-takes-agency',
    label: 'Hot Takes: Marketing Agency Industry',
    desc: 'The uncomfortable truths about running a marketing agency',
    icon: '🔥',
    category: 'Hot Takes',
    format: 'hot-take',
    topic: 'Unpopular truths about the marketing agency business that agency owners need to hear',
    cards: [
      { type: 'cover', eyebrow: 'HOT TAKES', headline: 'UNCOMFORTABLE TRUTHS ABOUT RUNNING A MARKETING AGENCY', subheadline: 'The stuff nobody says out loud. Here it is.', tag: 'AGENCY LIFE' },
      { type: 'hot-take', eyebrow: 'TRUTH #1', headline: 'MOST AGENCIES SELL MARKETING AND DO NOT DO ANY', body: 'The agency that posts once a week on their own channels, has 14 Google reviews, and has not sent an email campaign in 3 months is the same agency selling you a $3,000/month marketing retainer. Your agency should be the best-marketed business in your portfolio. If you would not hire yourself, why should anyone else?', slideNumber: 1, totalSlides: 6 },
      { type: 'hot-take', eyebrow: 'TRUTH #2', headline: 'GENERALIST AGENCIES ARE DYING', body: '"We do social media, SEO, email, PPC, web design, and branding for any business in any industry." That sentence is worth nothing in 2024. The agencies winning are the ones that do one thing for one type of business better than anyone else. Niche specificity is the moat. Generalism is a race to the bottom on price.', slideNumber: 2, totalSlides: 6 },
      { type: 'hot-take', eyebrow: 'TRUTH #3', headline: 'CHURN IS A PRODUCT PROBLEM, NOT A SALES PROBLEM', body: 'If you are replacing 20-30% of your clients every year you do not have a sales problem — you have a results problem. Agencies that retain clients do so because they produce outcomes the client can see and measure. Churn is clients voting with their feet that the value was not clear enough to justify the invoice.', slideNumber: 3, totalSlides: 6 },
      { type: 'hot-take', eyebrow: 'TRUTH #4', headline: 'DONE-FOR-YOU BEATS DONE-WITH-YOU AT EVERY PRICE POINT', body: 'Coaching and consulting agencies charge $500-1,500/month to teach clients to do marketing themselves. Done-for-you agencies charge $1,500-5,000/month to just do it. The DFY client stays 3x longer because they are busy running their business. The coaching client churns when they realize they do not have time to do the work.', slideNumber: 4, totalSlides: 6 },
      { type: 'hot-take', eyebrow: 'TRUTH #5', headline: 'THE BEST MARKETING AGENCIES CLOSE ON DEMOS, NOT PROPOSALS', body: 'Sending a 12-page proposal and waiting is how agencies lose deals. Showing the prospect their competitor\'s results, their own missed opportunities, and a live demo of what you would build — and asking for the business in that meeting — closes 3x the rate of any proposal you will ever write.', slideNumber: 5, totalSlides: 6 },
      { type: 'cta', eyebrow: 'THE TRUTH', headline: 'THE AGENCIES WINNING HAVE DONE THE OPPOSITE OF ALL OF THIS', body: 'Niched, results-driven, done-for-you, demo-close, low-churn. That is the playbook.', ctaText: 'Follow For More' },
    ],
  },
  {
    id: 'hot-takes-sales',
    label: 'Hot Takes: Sales Truth Nobody Admits',
    desc: 'The uncomfortable truths about sales that close more deals',
    icon: '🔥',
    category: 'Hot Takes',
    format: 'hot-take',
    topic: 'Unpopular truths about sales that most salespeople and business owners refuse to admit',
    cards: [
      { type: 'cover', eyebrow: 'HOT TAKES', headline: 'SALES TRUTHS NOBODY WANTS TO ADMIT', subheadline: 'The stuff that makes people uncomfortable. And closes more deals.', tag: 'SALES REALITY' },
      { type: 'hot-take', eyebrow: 'TRUTH #1', headline: 'MOST PEOPLE LOSE DEALS BEFORE THEY OPEN THEIR MOUTH', body: 'Response time is the first filter. If you take 3 hours to call back a new lead, 40% of them have already moved on. Studies consistently show companies that respond in under 5 minutes close 9x more leads than companies that respond in an hour. The sale was yours before the first word — you just gave it away by being slow.', slideNumber: 1, totalSlides: 6 },
      { type: 'hot-take', eyebrow: 'TRUTH #2', headline: '"ALWAYS BE CLOSING" IS WHY YOU ARE LOSING', body: 'The harder you push, the more resistance you create. The best salespeople ask better questions and let the prospect close themselves. When a customer says "I\'m ready to move forward" after answering your questions — that is not a coincidence. That is NEPQ. That is Challenger. That is what actually works in 2024.', slideNumber: 2, totalSlides: 6 },
      { type: 'hot-take', eyebrow: 'TRUTH #3', headline: 'MOST OBJECTIONS ARE NOT THE REAL OBJECTION', body: '"Your price is too high" usually means "I don\'t trust you enough yet." "I need to think about it" usually means "I have a concern I haven\'t told you." "Let me talk to my partner" often means "I\'m not convinced." Salespeople who take objections at face value lose. The ones who ask "what specifically?" win.', slideNumber: 3, totalSlides: 6 },
      { type: 'hot-take', eyebrow: 'TRUTH #4', headline: 'FOLLOWING UP 7 TIMES IS NOT ANNOYING — IT IS NECESSARY', body: 'The data: 80% of sales require 5 or more follow-ups. 44% of salespeople give up after 1 follow-up. If you follow up once and stop — you are competing with nobody because the other 44% already quit. The deals in your pipeline right now are waiting to be closed by whoever follows up next.', slideNumber: 4, totalSlides: 6 },
      { type: 'hot-take', eyebrow: 'TRUTH #5', headline: 'DISCOUNTING IS ADMITTING YOU CANNOT SELL', body: 'Every time you drop your price without asking for something in return, you train the customer that your price was arbitrary, signal that margins are huge, and teach them to negotiate harder next time. Instead: offer a payment plan, add a bonus, improve the timeline. The price holds. The perceived value increases.', slideNumber: 5, totalSlides: 6 },
      { type: 'cta', eyebrow: 'THE TRUTH', headline: 'THE SALESPEOPLE WINNING DO ALL OF THIS DIFFERENTLY', body: 'Speed to lead, question-based selling, objection handling, and automated follow-up — the full system.', ctaText: 'Follow For More' },
    ],
  },

  // ══════════════════════════════════════════
  // NEW NICHES — Local Service Businesses
  // ══════════════════════════════════════════
  {
    id: 'med-spa-marketing',
    label: 'Med Spa: Marketing That Fills the Schedule',
    desc: 'How aesthetic clinics and med spas grow without discounting',
    icon: '💆',
    category: 'Industry: Med Spa & Aesthetics',
    format: 'lesson',
    topic: 'How med spas and aesthetic clinics market themselves to fill their schedule without constant discounting',
    cards: [
      { type: 'cover', eyebrow: 'MED SPA MARKETING', headline: 'HOW TO FILL YOUR MED SPA SCHEDULE WITHOUT DISCOUNTING', subheadline: 'The marketing moves that build a loyal client base that books on repeat — without Groupon or flash sales.', tag: 'AESTHETICS BUSINESS' },
      { type: 'lesson', eyebrow: 'THE PROBLEM', headline: 'DISCOUNTING TRAINS YOUR CLIENTS TO WAIT', bullets: ['Every Groupon or half-off promotion teaches clients your real price is negotiable', 'Deep discount clients have the lowest retention rate and the lowest referral rate', 'You attract price shoppers — the least loyal segment in any market', 'Breaking the discount cycle requires 3-6 months of discipline but pays compounding dividends'], lesson: 'The clients who pay full price refer the most, complain the least, and stay the longest. Discounting filters them out.', lessonLabel: 'THE REALITY', slideNumber: 1, totalSlides: 6 },
      { type: 'lesson', eyebrow: 'THE STRATEGY', headline: 'MEMBERSHIP PROGRAMS — THE RECURRING REVENUE MODEL', bullets: ['$99-$199/month membership: includes 1 treatment credit + 10-15% off everything else', 'Average member visits 2x more frequently than non-member', 'Retention rate: members at 85%+ vs one-time clients at 30-40%', 'Predictable monthly revenue makes staffing and inventory planning simple'], lesson: 'A med spa with 200 members has $20,000-$40,000 in recurring revenue before the month even starts.', lessonLabel: 'THE SHIFT', slideNumber: 2, totalSlides: 6 },
      { type: 'lesson', eyebrow: 'THE CONTENT', headline: 'THE CONTENT THAT CONVERTS FOR AESTHETICS', bullets: ['Before/after photos with client permission — the highest-converting content in aesthetics', 'Provider education content: "3 things to know before your first Botox appointment"', 'Treatment myth-busters: "Filler doesn\'t have to look fake — here is why"', 'Behind the scenes: provider doing their own treatments, morning routines, honest Q&As'], lesson: 'Clients choose aesthetic providers based on trust in their skill. Educational content builds that trust before the consultation.', lessonLabel: 'THE APPROACH', slideNumber: 3, totalSlides: 6 },
      { type: 'lesson', eyebrow: 'THE RETENTION', headline: 'THE REBOOKING SYSTEM THAT KEEPS CLIENTS COMING BACK', bullets: ['Rebook at the appointment: "Your next treatment will be most effective in 12 weeks — want to grab that spot now?"', 'Automated touch-up reminders: 2 weeks before optimal rebook window', 'Post-treatment check-in text at 2 weeks: "How are you loving your results?"', 'Birthday month bonus: members get a complimentary add-on in their birthday month'], lesson: 'The provider who stays in contact between visits builds a relationship. The one who only sees clients during appointments loses them to whoever reaches out first.', lessonLabel: 'THE SYSTEM', slideNumber: 4, totalSlides: 6 },
      { type: 'stat', eyebrow: 'THE MATH', stat: '$4,200', statLabel: 'Average annual revenue per retained med spa client vs $380 for a one-time client', body: 'The math is simple: acquire clients, retain them on a membership, and the economics of a med spa become extraordinary. The problem is most clinics focus 90% on acquisition and almost nothing on retention.', slideNumber: 5, totalSlides: 6 },
      { type: 'cta', eyebrow: 'BUILD THE SYSTEM', headline: 'WANT A MEMBERSHIP, RETENTION, AND REACTIVATION SYSTEM BUILT FOR YOUR MED SPA?', body: 'Membership enrollment automation, rebooking sequences, and post-treatment follow-up — done for you.', ctaText: 'Book a Free Demo' },
    ],
  },
  {
    id: 'dentist-marketing',
    label: 'Dental Practice: Marketing That Fills Chairs',
    desc: 'How dental practices grow new patient volume and reduce no-shows',
    icon: '🦷',
    category: 'Industry: Dental & Medical',
    format: 'lesson',
    topic: 'How dental practices generate new patients and reduce no-shows with better marketing and automation',
    cards: [
      { type: 'cover', eyebrow: 'DENTAL MARKETING', headline: 'HOW TO FILL YOUR CHAIRS AND KEEP THEM FULL', subheadline: 'The patient acquisition and retention system for dental practices that want consistent growth.', tag: 'DENTAL PRACTICE' },
      { type: 'lesson', eyebrow: 'THE REALITY', headline: 'MOST DENTAL MARKETING IS PASSIVE AND INVISIBLE', bullets: ['A nice website with no traffic is a digital brochure nobody reads', 'Yellow Pages is dead — your patients are deciding on Google reviews first', 'The practice with 150 Google reviews at 4.9 stars owns new patient calls in any local market', 'Word of mouth works — but it caps at the size of your existing patient network'], lesson: 'Dental practices that are not actively generating visibility are slowly becoming invisible.', lessonLabel: 'THE PROBLEM', slideNumber: 1, totalSlides: 6 },
      { type: 'lesson', eyebrow: 'THE ACQUISITION', headline: 'THE 3 CHANNELS THAT GENERATE NEW DENTAL PATIENTS', bullets: ['Google Local Services Ads: pay per verified lead call — shows above everything in search', 'Review management: 4.8+ stars at 100+ reviews means you win every comparison', 'Facebook/Instagram: "New patients welcome — no insurance required" campaigns to homeowners 35-65 within 10 miles'], lesson: 'New patient acquisition for dental is a local visibility game. The most visible practice wins most of the unaffiliated patients in the market.', lessonLabel: 'THE CHANNELS', slideNumber: 2, totalSlides: 6 },
      { type: 'lesson', eyebrow: 'THE NO-SHOW PROBLEM', headline: 'REDUCE NO-SHOWS BY 60% WITH THIS SEQUENCE', bullets: ['Appointment booked → confirmation text immediately with date, time, and what to bring', '72 hours before: reminder text with rescheduling option', '24 hours before: reminder text requesting confirmation reply', '2 hours before: final text with office address and parking info', 'No-show → call within 15 minutes + rescheduling text within 1 hour'], lesson: 'The average dental practice loses $40,000-$80,000 per year to no-shows. A 5-touch confirmation sequence cuts that in half.', lessonLabel: 'THE SYSTEM', slideNumber: 3, totalSlides: 6 },
      { type: 'lesson', eyebrow: 'THE RETENTION', headline: 'REACTIVATE LAPSED PATIENTS — YOUR MOST OVERLOOKED REVENUE', bullets: ['Patients who miss their 6-month recall are your highest-probability new bookings', '"It has been 9 months since your last cleaning — we wanted to make sure you are taken care of" text converts at 25-35%', 'Lapsed patient campaigns run in January and September consistently fill schedules', 'Each reactivated patient is worth $600-$2,000 per year in revenue'], lesson: 'Most dental practices have hundreds of lapsed patients sitting in their system generating zero revenue. One campaign changes that.', lessonLabel: 'THE OPPORTUNITY', slideNumber: 4, totalSlides: 6 },
      { type: 'stat', eyebrow: 'THE NUMBERS', stat: '$180k', statLabel: 'Average annual revenue impact of adding 50 new active patients per year', body: 'At $3,600 average annual value per active patient — 50 new patients per year compounds into a dramatically different practice in 3-5 years. The practices doing this are not working harder — they just have better systems.', slideNumber: 5, totalSlides: 6 },
      { type: 'cta', eyebrow: 'BUILD THE SYSTEM', headline: 'WANT NEW PATIENT ACQUISITION AND REACTIVATION BUILT FOR YOUR PRACTICE?', body: 'Review automation, appointment confirmation sequences, lapsed patient reactivation — all done for you.', ctaText: 'Book a Free Demo' },
    ],
  },
  {
    id: 'car-detailing-marketing',
    label: 'Auto Detailing: Marketing That Books Jobs',
    desc: 'How car detailers build recurring clients and premium pricing',
    icon: '🚗',
    category: 'Industry: Auto Services',
    format: 'lesson',
    topic: 'How car detailing businesses build recurring revenue, premium pricing, and a loyal client base',
    cards: [
      { type: 'cover', eyebrow: 'AUTO DETAILING', headline: 'HOW TO BUILD A DETAILING BUSINESS THAT RUNS ON REPEAT CLIENTS', subheadline: 'The moves that separate a $60k detailer from a $300k detailing operation.', tag: 'AUTO DETAILING' },
      { type: 'lesson', eyebrow: 'THE PRICING TRAP', headline: 'STOP COMPETING ON PRICE — START COMPETING ON OUTCOME', bullets: ['The Groupon detailer gets $80 for a full detail. The premium detailer gets $350 for the same time.', 'The difference is not the service — it is the positioning, the presentation, and the before/after documentation', '"Showroom condition guaranteed" beats "affordable detailing" in the mind of someone who cares about their car', 'Target the right customer: enthusiasts, luxury vehicle owners, pre-sale sellers — not price shoppers'], lesson: 'The right customer will gladly pay 4x what the wrong customer will. Find the right customer first.', lessonLabel: 'THE SHIFT', slideNumber: 1, totalSlides: 5 },
      { type: 'lesson', eyebrow: 'THE RECURRING MODEL', headline: 'MONTHLY DETAIL PROGRAMS — THE COMPOUNDING REVENUE MODEL', bullets: ['$149/month program: exterior wash and interior wipe monthly + 1 full detail per quarter', 'Car enthusiasts, luxury owners, and dealers will pay for predictable service', 'A client on a monthly program is worth $1,788/year vs $350 for a single detail', '20 program clients = $35,760 guaranteed annual revenue before you take a single call'], lesson: 'Recurring detail programs are the subscription model of the auto industry. The setup is simple. The math is compelling.', lessonLabel: 'THE OPPORTUNITY', slideNumber: 2, totalSlides: 5 },
      { type: 'lesson', eyebrow: 'THE CONTENT', headline: 'THE CONTENT THAT SELLS PREMIUM DETAILING', bullets: ['Time-lapse before/after videos: one of the highest-performing content formats on social', 'Document specialty jobs: ceramic coatings, paint correction, vintage restorations', 'Education content: "3 things that are destroying your car\'s paint right now"', 'Post in local car enthusiast Facebook groups and Instagram with location tags'], lesson: 'The transformation content you create for each job is your portfolio. It sells for you while you work.', lessonLabel: 'THE STRATEGY', slideNumber: 3, totalSlides: 5 },
      { type: 'quick-win', eyebrow: 'DO THIS NOW', headline: 'TEXT YOUR LAST 20 CLIENTS ABOUT A PROGRAM', body: '"Hey [name], it\'s [your name]. I wanted to let you know I am offering a monthly detail program — it locks in priority scheduling, saves you 20% vs booking individually, and keeps your car in the condition you love year-round. Interested in hearing the details?" Expect 25-35% to say yes immediately.', lesson: 'Your existing clients are your best prospects for a recurring program. They already know the value of your work.', lessonLabel: 'THE QUICK WIN', slideNumber: 4, totalSlides: 5 },
      { type: 'cta', eyebrow: 'BUILD IT', headline: 'WANT YOUR DETAILING PROGRAM AND REACTIVATION CAMPAIGNS BUILT?', body: 'Program enrollment automation, before/after content strategy, and client retention sequences — done for you.', ctaText: 'Book a Free Demo' },
    ],
  },
  {
    id: 'concrete-marketing',
    label: 'Concrete & Hardscaping: Marketing That Closes',
    desc: 'How concrete and hardscape contractors win high-ticket jobs',
    icon: '🏗️',
    category: 'Industry: Concrete & Hardscaping',
    format: 'lesson',
    topic: 'How concrete and hardscaping contractors market to close high-ticket driveway, patio, and retaining wall jobs',
    cards: [
      { type: 'cover', eyebrow: 'CONCRETE MARKETING', headline: 'HOW CONCRETE CONTRACTORS WIN HIGH-TICKET JOBS WITHOUT BEING THE CHEAPEST', subheadline: 'The marketing and sales system for concrete and hardscape contractors who want better jobs at better margins.', tag: 'CONCRETE & HARDSCAPE' },
      { type: 'lesson', eyebrow: 'THE MARKET', headline: 'CONCRETE IS A HIGH-CONSIDERATION PURCHASE', bullets: ['A driveway replacement is $8,000-$25,000 — homeowners research for weeks before calling', 'The contractor who shows up first in search AND has the best visual portfolio wins most of these calls', 'Before/after photos of driveways, patios, and retaining walls are the single most important sales asset', 'Reviews matter enormously — 92% of homeowners read reviews before contacting any contractor over $5,000'], lesson: 'Concrete jobs are not impulse purchases. The homeowner who finds you has already decided to spend. Your job is to be found and trusted before they call anyone else.', lessonLabel: 'THE REALITY', slideNumber: 1, totalSlides: 5 },
      { type: 'lesson', eyebrow: 'THE PORTFOLIO', headline: 'YOUR PHOTOS ARE YOUR BEST SALESPERSON', bullets: ['Every completed job deserves 10-15 photos: before, during, and after', 'Drone shots of large projects convert at 2-3x the rate of ground-level photos', 'Video walkthroughs posted to Instagram and YouTube rank locally and generate long-term leads', 'A Google Business Profile with 50+ project photos dominates the map pack in most markets'], lesson: 'The concrete contractor with the best photo portfolio wins the job before the first phone call. Build it obsessively.', lessonLabel: 'THE STRATEGY', slideNumber: 2, totalSlides: 5 },
      { type: 'lesson', eyebrow: 'THE ESTIMATE', headline: 'WHY YOUR ESTIMATE IS LOSING JOBS', bullets: ['A one-page estimate with a total number loses to a detailed estimate with line items every time', 'Include: scope description, materials used, timeline, what they can expect during work, warranty', 'Add 3-5 project photos similar to their scope directly in the estimate document', 'Include a comparison of "repair vs replace" when applicable — positions you as an advisor, not a vendor'], lesson: 'The contractor who helps the homeowner understand their decision wins the job. The one who just sends a number loses to whoever was more educational.', lessonLabel: 'THE DIFFERENCE', slideNumber: 3, totalSlides: 5 },
      { type: 'quick-win', eyebrow: 'DO THIS WEEK', headline: 'POST YOUR LAST 3 COMPLETED JOBS TO NEXTDOOR AND LOCAL FACEBOOK GROUPS', body: '"Just finished this driveway replacement in [neighborhood] — the homeowner wanted something that would last 25+ years and look great from the street. Happy to give free estimates to any neighbors considering the same." Include 3-4 photos. Post in the neighborhood group where the job was located. Expect 3-8 direct messages per post.', lesson: 'Nextdoor and local Facebook groups are the highest-quality free lead source for concrete in any local market.', lessonLabel: 'DO THIS NOW', slideNumber: 4, totalSlides: 5 },
      { type: 'cta', eyebrow: 'BUILD THE SYSTEM', headline: 'WANT YOUR CONCRETE MARKETING AND FOLLOW-UP BUILT?', body: 'Estimate follow-up sequences, review automation, and lead generation system — done for you.', ctaText: 'Book a Free Demo' },
    ],
  },
  {
    id: 'marketing-agency-growth',
    label: 'Marketing Agency: How to Get Clients',
    desc: 'The client acquisition system for marketing agencies',
    icon: '📊',
    category: 'Industry: Marketing Agency',
    format: 'lesson',
    topic: 'How marketing agencies get clients consistently — outbound, content, and referral strategies that work',
    cards: [
      { type: 'cover', eyebrow: 'AGENCY GROWTH', headline: 'HOW MARKETING AGENCIES GET CLIENTS CONSISTENTLY', subheadline: 'The acquisition system for agencies that are tired of feast-or-famine revenue.', tag: 'AGENCY BUSINESS' },
      { type: 'lesson', eyebrow: 'THE IRONY', headline: 'MOST MARKETING AGENCIES ARE THE WORST-MARKETED BUSINESSES IN THEIR MARKET', bullets: ['The agency with 12 Google reviews selling reputation management', 'The agency with no email list selling email marketing services', 'The agency with 400 Instagram followers selling social media management', 'If you would not hire yourself based on your own marketing — your prospects see the same thing'], lesson: 'Your agency is your best case study. Market it better than any client you have ever taken on.', lessonLabel: 'START HERE', slideNumber: 1, totalSlides: 6 },
      { type: 'lesson', eyebrow: 'THE OUTBOUND', headline: 'THE OUTREACH SYSTEM THAT BOOKS DEMOS', bullets: ['Identify 50 businesses in your niche that are missing the specific thing you do', 'Cold email: one specific observation about their business + one specific problem it causes + one question', 'Follow up 6 times minimum — most responses come on touch 4-6', 'LinkedIn DM: comment on their content 3 times before the first DM — never pitch cold'], lesson: 'Outbound that leads with a specific insight about the prospect converts 4-6x better than outbound that leads with your offer.', lessonLabel: 'THE APPROACH', slideNumber: 2, totalSlides: 6 },
      { type: 'lesson', eyebrow: 'THE CONTENT', headline: 'THE CONTENT THAT GENERATES INBOUND AGENCY LEADS', bullets: ['Case studies with specific numbers: "How we helped a [niche] company go from $X to $Y in 90 days"', 'Process content: "The exact 5-step system we use for every new client onboarding"', 'Hot take content: "The biggest mistake [niche] businesses make with their marketing"', 'LinkedIn and YouTube outperform Instagram for B2B agency client acquisition by 3-5x'], lesson: 'Agencies that publish their process and results attract clients who already believe in their approach. The sales call becomes a formality.', lessonLabel: 'THE STRATEGY', slideNumber: 3, totalSlides: 6 },
      { type: 'lesson', eyebrow: 'THE CLOSE', headline: 'CLOSE ON THE DEMO — NOT ON A PROPOSAL', bullets: ['Show them their competitor\'s results during the demo using real data and tools', 'Show them exactly what you would build for them — mockups, workflow screenshots, strategy doc', 'Ask for the business before the call ends: "Based on everything we have covered — does this feel like a fit?"', 'A proposal sent after the demo is a follow-up document, not a sales tool'], lesson: 'Agencies that close on the demo close at 40-60%. Agencies that send proposals and follow up close at 15-20%. The demo is the close.', lessonLabel: 'THE PROCESS', slideNumber: 4, totalSlides: 6 },
      { type: 'stat', eyebrow: 'THE TARGET', stat: '80%', statLabel: 'Retention rate of agencies that produce measurable results vs 40% for those that do not track outcomes', body: 'Client acquisition gets you to revenue. Client retention gets you to profit. Every dollar spent keeping an existing client is worth $5 spent acquiring a new one. Your retention rate is your business health metric.', slideNumber: 5, totalSlides: 6 },
      { type: 'cta', eyebrow: 'YOUR SYSTEM', headline: 'WHAT DOES YOUR AGENCY\'S CLIENT ACQUISITION SYSTEM LOOK LIKE?', body: 'If you are winging it with referrals and hope — this is the moment to build something that runs consistently.', ctaText: 'Follow For More' },
    ],
  },
  {
    id: 'nail-salon-marketing',
    label: 'Nail Salon: Fill Your Books Without Discounting',
    desc: 'How nail salons build loyal clientele and recurring revenue',
    icon: '💅',
    category: 'Industry: Beauty & Salon',
    format: 'lesson',
    topic: 'How nail salons and beauty businesses build a loyal clientele and fill their appointment books consistently',
    cards: [
      { type: 'cover', eyebrow: 'SALON MARKETING', headline: 'HOW TO FILL YOUR NAIL SALON WITHOUT DISCOUNTING', subheadline: 'The loyalty and retention system that keeps your books full year-round.', tag: 'NAIL SALON' },
      { type: 'lesson', eyebrow: 'THE RETENTION MATH', headline: 'ONE LOYAL CLIENT IS WORTH 10 NEW ONES', bullets: ['Regular client comes every 3 weeks: 17 visits per year at $65 average = $1,105/year', 'They refer 2-3 friends who each become regular clients', 'They rebook at the chair — no marketing cost, no no-show risk, no acquisition cost', 'Losing one loyal client to a competitor costs $1,500-$3,000 in lifetime revenue'], lesson: 'The nail salon that obsesses over retention will always outperform the one that chases new clients.', lessonLabel: 'THE MATH', slideNumber: 1, totalSlides: 5 },
      { type: 'lesson', eyebrow: 'THE SYSTEM', headline: 'REBOOK BEFORE THEY LEAVE THE CHAIR', bullets: ['"Same time in 3 weeks?" asked at every appointment captures 60-70% of bookings on the spot', 'Clients who leave without rebooking show at 40% for their next visit', 'Clients who leave with a booking show at 85-90%', 'A simple confirmation text 24 hours before the appointment cuts no-shows by 50%'], lesson: 'The 10 seconds it takes to ask "same time in 3 weeks?" is the highest-ROI activity in your entire business.', lessonLabel: 'THE TACTIC', slideNumber: 2, totalSlides: 5 },
      { type: 'lesson', eyebrow: 'THE CONTENT', headline: 'THE INSTAGRAM CONTENT THAT DRIVES BOOKINGS', bullets: ['Nail art close-ups with natural lighting — the primary content that converts for salons', 'Client spotlight: tag the client (with permission) in their set reveal', '"DM me BOOK" automation: 20-30% of DMs convert to bookings when there is an easy next step', 'Behind the scenes content outperforms polished ads — authenticity builds trust faster'], lesson: 'Instagram is the primary search engine for nail clients. Your profile is your storefront. Make it irresistible.', lessonLabel: 'THE PLATFORM', slideNumber: 3, totalSlides: 5 },
      { type: 'quick-win', eyebrow: 'DO THIS WEEK', headline: 'LAUNCH A LOYALTY PUNCH CARD — DIGITAL OR PHYSICAL', body: '"Visit 10 times and your 11th service is free." Simple. Trackable. Proven. Clients with loyalty programs visit 35% more frequently and refer twice as often. A digital version via GHL or a simple app sends automated stamps and reward notifications. Your highest-value clients will enroll immediately.', lesson: 'Loyalty programs are retention tools, not discounts. The client earns the reward by being loyal — you win too.', lessonLabel: 'DO THIS WEEK', slideNumber: 4, totalSlides: 5 },
      { type: 'cta', eyebrow: 'BUILD IT', headline: 'WANT YOUR SALON BOOKING, LOYALTY, AND REACTIVATION SYSTEM BUILT?', body: 'Appointment reminders, loyalty tracking, and lapsed client reactivation — all automated.', ctaText: 'Book a Free Demo' },
    ],
  },
  {
    id: 'mechanic-marketing',
    label: 'Auto Repair: Marketing That Brings Cars Back',
    desc: 'How auto repair shops build repeat customers and beat the dealerships',
    icon: '🔧',
    category: 'Industry: Auto Services',
    format: 'lesson',
    topic: 'How independent auto repair shops market to get repeat customers and compete against dealerships',
    cards: [
      { type: 'cover', eyebrow: 'AUTO REPAIR MARKETING', headline: 'HOW INDEPENDENT SHOPS WIN LOYAL CUSTOMERS FROM DEALERSHIPS', subheadline: 'The marketing system that turns one-time repair customers into lifetime clients.', tag: 'AUTO REPAIR' },
      { type: 'lesson', eyebrow: 'THE ADVANTAGE', headline: 'YOU HAVE SOMETHING DEALERSHIPS NEVER WILL', bullets: ['Personal relationships — the service advisor who knows your name and your car\'s history', 'Trust — customers choose their mechanic like they choose their doctor', 'Price — independent shops average 20-40% less than dealerships for the same work', 'Speed — smaller shops often turn cars around same-day vs 2-3 days at a dealer'], lesson: 'Every independent shop has natural advantages over dealerships. Most fail to communicate them. The ones that do win the comparison every time.', lessonLabel: 'YOUR EDGE', slideNumber: 1, totalSlides: 5 },
      { type: 'lesson', eyebrow: 'THE SYSTEM', headline: 'THE MAINTENANCE REMINDER SYSTEM THAT BRINGS CARS BACK', bullets: ['Track every vehicle in your system with last service date and mileage', 'Text at 2,900 miles if last service was an oil change: "Your [make/model] is due for an oil change — want to get scheduled?"', 'Annual reminder for vehicles not seen in 12 months: "We have not seen your [car] in a while — is everything running well?"', 'Pre-season reminder: "Winter is coming — want us to check your battery, tires, and fluids?"'], lesson: 'The shop that reminds customers before they need a repair wins the business. The one that waits for them to call loses to whoever got there first.', lessonLabel: 'THE APPROACH', slideNumber: 2, totalSlides: 5 },
      { type: 'lesson', eyebrow: 'THE TRUST', headline: 'THE TRANSPARENCY CONTENT THAT ELIMINATES TRUST OBJECTIONS', bullets: ['"What does this repair actually involve?" — short educational videos filmed in the shop', 'Photo/video documentation of the actual problem sent to the customer before any work is approved', '"The honest answer to [common car myth]" — positions you as the trustworthy expert', 'Customer testimonial videos: "I have been coming here for 8 years because..."'], lesson: 'The biggest objection to auto repair is trust. Transparent educational content eliminates it before it is ever raised.', lessonLabel: 'THE CONTENT', slideNumber: 3, totalSlides: 5 },
      { type: 'quick-win', eyebrow: 'DO THIS WEEK', headline: 'TEXT YOUR LAPSED CUSTOMERS RIGHT NOW', body: '"Hey [name], it\'s [shop name]. We haven\'t seen your [car] since [date] — just wanted to check in and make sure everything is running well. If anything comes up or you are due for maintenance, we would love to take care of you. Give us a call or reply to this text." Expect 20-30% to respond. Several will book immediately.', lesson: 'Your lapsed customers already know and trust you. They just need to be reminded you exist.', lessonLabel: 'DO THIS NOW', slideNumber: 4, totalSlides: 5 },
      { type: 'cta', eyebrow: 'BUILD IT', headline: 'WANT YOUR AUTO SHOP CUSTOMER RETENTION SYSTEM BUILT AND RUNNING?', body: 'Maintenance reminders, lapsed customer reactivation, and review automation — all automated.', ctaText: 'Book a Free Demo' },
    ],
  },
];
